environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@5.3
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

version: '{build}'
build: off

shallow_clone: true
clone_depth: 1

matrix:
  fast_finish: true